name: Test

on: [push]

jobs:
  ruby:
    strategy:
      matrix:
        container: [ruby, jruby]
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.container }}
    container: docker://${{ matrix.container }}
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
