name: Test

on: [push]

jobs:
  ruby:
    runs-on: ubuntu-latest
    name: Ruby
    container: ruby
    steps:
    - uses: actions/checkout@master
    - name: Run tests
      run: |
        bundle install --jobs 4 --retry 3
        bundle exec rake
